### ISSUE TITLE
Add setting to limit number of issues posted to a pull request across multiple runs

### ISSUE THREAD

**Issue by janniksam** [cake-contrib/Cake.Issues.PullRequests#134]
Lets imagine, in theory, my pullrequest is fixing somehing in a old legacy classes and 200 warnings pop up during code analyse of my PRs build. Most of aren't results from by my changes. MaxIssuesToPost is set to 50 warnings, so 50 warnings will be output to the Pull Request..

Now I'll fix all the 50 warnings in my next commit to the PR. The build will be rerun and reanalyse everything. **Will it output the next 50 warnings or does it detect that it already detect the 50 submitted warnings?**

It already gave me 50, and I wouldn't want to fix another 50, when it comes to legacy code. We're aiming for small but steady steps to a zero warning policy. (currently we're at 14000 ;-))

**Comment by janniksam** [comment]
I really don't want to rush you and its not _that_ urgent.
But maybe you have a time estimate, whether it can take days or weeks or even months?

I might be able to check out the code myself and spend some of my free time and try to get a switch implemented for that feature.

**Comment by pascalberger** [comment]
@janniksam If you want to test you can checkout the changes from https://github.com/cake-contrib/Cake.Issues.PullRequests/pull/138 and build the addin locally. I can also later provide a beta version for testing once the PRs are merged.

It adds a new setting `ReportIssuesToPullRequestSettings.MaxIssuesToPostAcrossRuns` which is applied after `ReportIssuesToPullRequestSettings.MaxIssuesToPostForEachIssueProvider` and `ReportIssuesToPullRequestSettings.MaxIssuesToPost`.

Behavior is like this. Assuming you have the following issues:
- 70 issues of provider A
- 70 issues of provider B

And the following settings:
- MaxIssuesToPostForEachIssueProvider: 20
- MaxIssuesToPost: 30
- MaxIssuesToPostAcrossRuns: 55

The following will happen:
- 1. Run: 30 issues are posted but not more than 20 of either provider A or B
- If you fix the issues and run again: 25 issues are posted but not more than 20 of either provider A or B
- If you fix the issues and run again: The remaining 85 won't be posted in this pull request

**Comment by janniksam** [comment]
Looks pretty good 👍  Good job. Will test it tomorrow or maybe on monday.

BTW: I wonder, what happens on the first run. Which provider will win? Is it random (one provider will output 20 and one 10 issues) or is it distributed equally between both providers (each provider will output 15 issues)?

**Comment by pascalberger** [comment]
> BTW: I wonder, what happens on the first run. Which provider will win? Is it random (one provider will output 20 and one 10 issues) or is it distributed equally between both providers (each provider will output 15 issues)?

Issues are filtered by priority (higher priorities are kept) and issues with a file path are prioritized over issues without a file path. Beside that it is undetermined.

**Comment by janniksam** [comment]
Hey Pascal. Did you create a beta release for this feature? I would be interested in that. 👍

**Comment by pascalberger** [comment]
Not yet, but can create a beta version later today

**Comment by pascalberger** [comment]
@janniksam I've released [0.8.1-beta0001](https://www.nuget.org/packages/Cake.Issues.PullRequests/0.8.1-beta0001) containing this feature
