### ISSUE TITLE
Add IIssueProvider.ProviderType

### ISSUE THREAD

**Issue by janniksam** [cake-contrib/Cake.Issues.PullRequests#169]
In 0.9.0 we added a new way of filtering issues by assigning each `ProviderType` some provider-specific issue limits.

Testing this on a real system I started to question myself:
Why did we decide to use `ProviderType` to define those limits:
https://github.com/cake-contrib/Cake.Issues.PullRequests/blob/release/0.9.0/src/Cake.Issues.PullRequests/IssueFilterer.cs#L264

 Why didn't we use `ProviderName`? Do we have no information at that point? Is the information lost and not saved to / read back from the pullrequest comments?

**Comment by pascalberger** [comment]
`ProviderType` is the technical identifier of a provider, while `ProviderName` is the human readable version. So this seems correct to me.

What's the actual issue you experience? What doesn't not work with `ProviderType` and would be solved with using `ProviderName`?

**Comment by janniksam** [comment]
In my real life example I do have to `IIssueProvider` which I read issues with.

After reading the issues I set up the filter settings for my azure devops pullrequest comments.
For setting my provider specific filters, I need the `ProviderType` from both providers. But `IIssueProvider` does only expose `ProviderName` and not the required `ProviderType` (https://github.com/cake-contrib/Cake.Issues/blob/release/0.9.0/src/Cake.Issues/IIssueProvider.cs).

We would need a better way to get the provider type for each `IIssueProvider`. Something easier than doing something like `ReadIssues().First().ProviderType`.

**Comment by pascalberger** [comment]
There are aliases to get provider type name (e.g. [MsBuildIssuesProviderTypeName](https://cakeissues.net/api/Cake.Issues.MsBuild/MsBuildIssuesAliases/0A221402).

**Comment by janniksam** [comment]
Any particular reason, why it is not part of the `IIssueProvider` interface?

**Comment by pascalberger** [comment]
There are valid use cases for an alias which returns provider type (e.g. if you want to implement a build breaking at the end of the build based on issues reported during build by a specific issue provider).

But adding `ProviderType` also to `IIssueProvider`, and not only have it as static property on the issue provider, might be an option.

**Comment by janniksam** [comment]
Right now, I have to call every providers alias method instead of just having a `provider.ProviderType`  property.

I would like this change. It doesnt have to be in the upcoming release 0.9.0, but in the long term I would consider it.

**Comment by janniksam** [comment]
Closed because this is the wrong repository.
