### ISSUE TITLE
Setting a ProviderLimit to zero will ignore the limit instead of posting 0 items

### ISSUE THREAD

**Issue by janniksam** [cake-contrib/Cake.Issues.PullRequests#173]
When setting on of the ProviderLimits to zero, it will report all instead of zero issues.

https://github.com/cake-contrib/Cake.Issues.PullRequests/blob/e001ee38a39dd3cc23b6b239f0c64251333ccbe8/src/Cake.Issues.PullRequests/IssueFilterer.cs#L307

I have a case in our production system, where I would like to 0 in some cases.

**Comment by phlorian** [comment]
This is a bug. The property is nullable, and this means, that the correct behaviour would be:
- With a value 0 or greater, use this value.
- If the provided value is null, then report all.
- Negative values do not make sense. I would treat them as zero.

What do you think? @janniksam @pascalberger

**Comment by janniksam** [comment]
Thats what what I would go for. 👍 In my initial implementation I just hadn't thought about those cases. ;)
